{
  "adapter": {
    "excluded_ops": [
      "LayerNorm"
    ],
    "input_quantization": true,
    "quantize_first_layer": false,
    "quantized_ops": [
      "all"
    ],
    "type": "generic",
    "weight_quantization": false
  },
  "adapter_type": "generic",
  "dataset": {
    "batch_size": 128,
    "name": "imagenet",
    "num_workers": 16,
    "path": "/data/imagenet/val"
  },
  "evaluation": {},
  "model": {
    "name": "mobilevit_xxs",
    "weights": "DEFAULT"
  },
  "output_name": "",
  "quantization": {
    "calib_method": "max",
    "chunk_size": 128,
    "format": "fp8_e1m6",
    "input_format": "fp8_e1m6",
    "mode": "chunk",
    "rounding": "nearest",
    "weight_chunk_size": 128,
    "weight_mode": "tensor"
  },
  "resolved_adapter_kwargs": {
    "act_chunk_size": null,
    "act_mode": "tensor",
    "chunk_size": 128,
    "excluded_ops": [
      "LayerNorm","BatchNorm2d"
    ],
    "fold_layers": false,
    "input_chunk_size": 128,
    "input_quantization": true,
    "input_quantization_type": "fp8_e1m6",
    "layer_config": null,
    "model_name": "mobilevit_xxs",
    "model_source": "auto",
    "per_chunk_format": false,
    "quant_mode": "chunk",
    "quantization_bias": null,
    "quantization_type": "fp8_e1m6",
    "quantize_first_layer": true,
    "quantized_ops": [
      "all"
    ],
    "rounding": "nearest",
    "run_id": "default",
    "simulate_tf32_accum": false,
    "skip_calibration": false,
    "weight_chunk_size": 128,
    "weight_mode": "tensor",
    "weight_quantization": false,
    "weights": "DEFAULT"
  }
}